using UnityEngine;
using System.Collections;

using RakNet;

/*
public enum MessageID : byte
{
    ID_USER_CMD_BEGIN = DefaultMessageIDTypes.ID_USER_PACKET_ENUM,


    ID_PLAYER_POS = 140,
    ID_PLAYER_POS_RSP,

    ID_NEED_CRC_BEGIN,

    ID_PLAYER_ENTERROOM,
    ID_PLAYER_ENTERROOM_RSP,
    ID_PLAYER_EXITROOM,

    ID_PLAYER_EXIT_INSTANCE,
    ID_PLAYER_EXIT_INSTANCE_RSP,

    ID_PLAYER_DISCONNECT,

    ID_PLAYER_CHAT,
    ID_PLAYER_CHAT_RSP,

    ID_PLAYER_GET_USERID,
    ID_PLAYER_GET_USERID_RSP,

    ID_PLAYER_ATTACK,
    ID_PLAYER_ATTACK_RSP,

    ID_PLAYER_REVIVE,
    ID_PLAYER_REVIVE_RSP,

    ID_PLAYER_DEAD,
    ID_PLAYER_DEAD_RSP,

    ID_PLAYER_LOGIN,
    ID_PLAYER_LOGIN_RSP,

    ID_PLAYER_HURT,
    ID_PLAYER_HURT_RSP,

    ID_PLAYER_TIMESTAMP,
    ID_PLAYER_TIMESTAMP_RSP,

    ID_PLAYER_START,
    ID_PLAYER_START_RSP,

    ID_PLAYER_STOP,
    ID_PLAYER_STOP_RSP,

    ID_PLAYER_CHANGE_SPEED,
    ID_PLAYER_CHANGE_SPEED_RSP,

    ID_PLAYER_CHANGE_DIR,
    ID_PLAYER_CHANGE_DIR_RSP,

    ID_MULTI_COMMAND = 249,

    ID_PROTOBUF_MSG = 250,
    ID_GAMESERVER_RSP = 251,
}
*/