//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: CLogin.proto
// Note: requires additional types generated from: ResultInfo.proto
// Note: requires additional types generated from: CUserInfo.proto
namespace network.message
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LoginRequest")]
  public partial class LoginRequest : global::ProtoBuf.IExtensible
  {
    public LoginRequest() {}
    
    private long _uid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"uid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long uid
    {
      get { return _uid; }
      set { _uid = value; }
    }
    private long _ttp;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"ttp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long ttp
    {
      get { return _ttp; }
      set { _ttp = value; }
    }
    private string _token;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"token", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string token
    {
      get { return _token; }
      set { _token = value; }
    }
    private string _udid;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"udid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string udid
    {
      get { return _udid; }
      set { _udid = value; }
    }
    private string _userName;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"userName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string userName
    {
      get { return _userName; }
      set { _userName = value; }
    }
    private int _accountType;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"accountType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int accountType
    {
      get { return _accountType; }
      set { _accountType = value; }
    }
    private int _serverId;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"serverId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int serverId
    {
      get { return _serverId; }
      set { _serverId = value; }
    }
    private string _version;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"version", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string version
    {
      get { return _version; }
      set { _version = value; }
    }
    private string _uid6w = "";
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"uid6w", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string uid6w
    {
      get { return _uid6w; }
      set { _uid6w = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LoginResponse")]
  public partial class LoginResponse : global::ProtoBuf.IExtensible
  {
    public LoginResponse() {}
    
    private network.message.Result _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public network.message.Result result
    {
      get { return _result; }
      set { _result = value; }
    }
    private network.message.UserInfo _userInfo = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"userInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public network.message.UserInfo userInfo
    {
      get { return _userInfo; }
      set { _userInfo = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"KickNtf")]
  public partial class KickNtf : global::ProtoBuf.IExtensible
  {
    public KickNtf() {}
    
    private network.message.Result _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public network.message.Result result
    {
      get { return _result; }
      set { _result = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}